#!/usr/bin/env python3
"""Generate sparse scanline metadata for the Home Dynamic cloud cache."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "USER" / "Res" / "yun" / "processed"
OUTPUT = ROOT / "USER" / "APP" / "home_theme2_cloud_sparse_rows.inc"
SHAPES = "abc"
STATES = "123"


def row_runs(path: Path) -> tuple[int, int, list[list[tuple[int, int]]]]:
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    rows: list[list[tuple[int, int]]] = []
    for y in range(image.height):
        values = alpha.crop((0, y, image.width, y + 1)).tobytes()
        runs: list[tuple[int, int]] = []
        start: int | None = None
        for x, value in enumerate(values + b"\0"):
            if value != 0 and start is None:
                start = x
            elif value == 0 and start is not None:
                runs.append((start, x - start))
                start = None
        rows.append(runs)
    return image.width, image.height, rows


def merge_runs(row_values: tuple[list[tuple[int, int]], ...]) -> list[tuple[int, int]]:
    intervals = sorted((start, start + length) for rows in row_values for start, length in rows)
    merged: list[list[int]] = []
    for start, end in intervals:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        elif end > merged[-1][1]:
            merged[-1][1] = end
    return [(start, end - start) for start, end in merged]


def emit_rows(lines: list[str], name: str, rows: list[list[tuple[int, int]]]) -> int:
    offset = 0
    segment_index = 0
    row_entries: list[tuple[int, int, int]] = []
    segment_entries: list[tuple[int, int, int]] = []
    for runs in rows:
        row_offset = offset
        row_entries.append((row_offset, segment_index, len(runs)))
        local_pixel = 0
        for x_start, length in runs:
            segment_entries.append((local_pixel, x_start, length))
            local_pixel += length
            segment_index += 1
        offset += local_pixel * 3

    lines.append(f"static const home_theme2_cloud_row_meta_t {name}_rows[] = {{")
    for payload_offset, first_segment, segment_count in row_entries:
        lines.append(f"    {{{payload_offset}U, {first_segment}U, {segment_count}U}},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const home_theme2_cloud_segment_meta_t {name}_segments[] = {{")
    for pixel_offset, x_start, length in segment_entries:
        lines.append(f"    {{{pixel_offset}U, {x_start}U, {length}U}},")
    lines.append("};")
    lines.append("")
    return offset


def main() -> None:
    lines = [
        "/* Generated by Tools/generate_home_cloud_sparse_rows.py. */",
        "/* Do not edit manually; row offsets are relative to each PSRAM image payload. */",
        "",
    ]
    resources: dict[tuple[str, str], tuple[str, int, int, int]] = {}
    runs_by_shape: dict[str, list[list[list[tuple[int, int]]]]] = {}

    for shape in SHAPES:
        runs_by_shape[shape] = []
        for state in STATES:
            width, height, rows = row_runs(SOURCE_DIR / f"cloud_{shape}_{state}.png")
            name = f"s_cloud_rows_{shape}_{state}"
            payload_size = emit_rows(lines, name, rows)
            resources[(shape, state)] = (name, width, height, payload_size)
            runs_by_shape[shape].append(rows)

    blend_resources: dict[tuple[str, str, str], tuple[str, int, int, int]] = {}
    for shape in SHAPES:
        state_rows = runs_by_shape[shape]
        for from_index, from_state in enumerate(STATES):
            for to_index in range(from_index, len(STATES)):
                to_state = STATES[to_index]
                if from_state == to_state:
                    blend_resources[(shape, from_state, to_state)] = resources[(shape, from_state)]
                    continue
                union_rows = [
                    merge_runs(row_values)
                    for row_values in zip(state_rows[from_index], state_rows[to_index])
                ]
                name = f"s_cloud_blend_rows_{shape}_{from_state}_{to_state}"
                payload_size = emit_rows(lines, name, union_rows)
                _, width, height, _ = resources[(shape, "1")]
                blend_resources[(shape, from_state, to_state)] = (name, width, height, payload_size)
                blend_resources[(shape, to_state, from_state)] = (name, width, height, payload_size)

    lines.append(
        "static const home_theme2_cloud_sparse_resource_t "
        "s_cloud_sparse_resources[HOME_THEME2_CLOUD_SHAPE_COUNT]"
        "[HOME_THEME2_CLOUD_STATE_COUNT] = {"
    )
    for shape in SHAPES:
        row = []
        for state in STATES:
            name, width, height, payload_size = resources[(shape, state)]
            row.append(f"{{{name}_rows, {name}_segments, {payload_size}U, {width}U, {height}U}}")
        lines.append("    {" + ", ".join(row) + "},")
    lines.append("};")
    lines.append("")
    lines.append(
        "static const home_theme2_cloud_sparse_resource_t "
        "s_cloud_blend_resources[HOME_THEME2_CLOUD_SHAPE_COUNT]"
        "[HOME_THEME2_CLOUD_STATE_COUNT][HOME_THEME2_CLOUD_STATE_COUNT] = {"
    )
    for shape in SHAPES:
        lines.append("    {")
        for from_state in STATES:
            row = []
            for to_state in STATES:
                name, width, height, payload_size = blend_resources[(shape, from_state, to_state)]
                row.append(f"{{{name}_rows, {name}_segments, {payload_size}U, {width}U, {height}U}}")
            lines.append("        {" + ", ".join(row) + "},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(
        "static const uint32_t "
        "s_cloud_blend_slot_payload_sizes[HOME_THEME2_CLOUD_SHAPE_COUNT] = {"
    )
    for shape in SHAPES:
        maximum = max(
            resource[3]
            for key, resource in blend_resources.items()
            if key[0] == shape
        )
        lines.append(f"    {maximum}U,")
    lines.append("};")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
