#ifndef __APP_EGUI_CONFIG_H__
#define __APP_EGUI_CONFIG_H__

/* STM32L471_FAN display: ST77903-style 428x142 RGB565 panel. */
#define EGUI_CONFIG_SCREEN_WIDTH  428
#define EGUI_CONFIG_SCREEN_HEIGHT 142
#define EGUI_CONFIG_COLOR_DEPTH   16

/* Existing LVGL port used LV_COLOR_16_SWAP=1 for SPI RGB565 byte order. */
#define EGUI_CONFIG_COLOR_16_SWAP 1

/* Two 10-line PFB buffers let SPI DMA flush one tile while the next tile renders. */
#define EGUI_CONFIG_PFB_WIDTH        EGUI_CONFIG_SCREEN_WIDTH
#define EGUI_CONFIG_PFB_HEIGHT       10
#define EGUI_CONFIG_PFB_BUFFER_COUNT 2

#define EGUI_CONFIG_MAX_FPS          30
#define EGUI_CONFIG_DIRTY_AREA_COUNT 4

/* No touch in this migration round. Physical keys remain enabled. */
#define EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH 0
#define EGUI_CONFIG_FUNCTION_SUPPORT_KEY   1
#define EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS 0

/* Keep the first port small and deterministic. */
#define EGUI_CONFIG_FUNCTION_SUPPORT_ACTIVITY 0
#define EGUI_CONFIG_FUNCTION_SUPPORT_DIALOG   0
#define EGUI_CONFIG_FUNCTION_SUPPORT_TOAST    0
#define EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW   0
#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK     1
#define EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR 0
#define EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG 0
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI   1
/* Row cache: ~12.5KB fixed, eliminates cross-tile re-decode within a frame */
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_FAST_DRAW 1
/* Persistent cache: 16KB heap, enough for bike image (12KB decoded) */
#define EGUI_CONFIG_IMAGE_CODEC_PERSISTENT_CACHE_MAX_BYTES 16384
#define EGUI_CONFIG_FUNCTION_FONT_TTF          0
#define EGUI_CONFIG_FUNCTION_FONT_STD_FAST_DRAW 0
#define EGUI_CONFIG_FUNCTION_FONT_TRANSFORM_FAST_DRAW 0

#define EGUI_CONFIG_FUNCTION_LABEL_TEXT_FMT  1
#define EGUI_CONFIG_FUNCTION_LABEL_LONG_MODE 1
#define EGUI_CONFIG_FUNCTION_LABEL_WORD_WRAP 1
#define EGUI_CONFIG_LABEL_FMT_BUF_SIZE       96

#define EGUI_CONFIG_DEBUG_LOG_LEVEL 0

/* Debug monitors: FPS/render time (bottom-right) and memory (bottom-left) */
#define EGUI_CONFIG_DEBUG_PERF_MONITOR_SHOW 1
#define EGUI_CONFIG_DEBUG_MEM_MONITOR_SHOW  1

#endif /* __APP_EGUI_CONFIG_H__ */
